version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing zip package..."
      - yum install -y zip       # Install zip on CodeBuild container
  build:
    commands:
      - echo "Building Spring Boot WAR for Elastic Beanstalk..."
      - mvn clean package -DskipTests
      - cp target/*.war ROOT.war
      - zip app.zip ROOT.war   # Zip ROOT.war at top level
artifacts:
  files:
    - app.zip
