version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing zip package..."
      - yum install -y zip

  build:
    commands:
      - echo "Building Spring Boot WAR for Elastic Beanstalk..."
      - mvn clean package -DskipTests

      # Create deploy folder
      - mkdir -p deploy

      # Copy WAR as ROOT.war (Elastic Beanstalk expects ROOT.war at top level)
      - cp target/*.war deploy/ROOT.war

      # Optional: verify WAR contents (JSP files)
      - echo "Listing JSP files in WAR for verification:"
      - unzip -l deploy/ROOT.war | grep ".jsp" || echo "No JSP files found in WAR"

      # Zip the deploy folder
      - cd deploy && zip -r ../app.zip . && cd ..

artifacts:
  files:
    - app.zip
