version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo "Building Spring Boot WAR for Elastic Beanstalk..."
      - mvn clean package -DskipTests
      - mkdir -p deploy
      - cp target/*.war ROOT.war
      - cd deploy && zip -r ../app.zip . && cd ..
artifacts:
  files:
    - app.zip
