version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing zip package..."
      - yum install -y zip unzip

  build:
    commands:
      - echo "Building Spring Boot WAR for Elastic Beanstalk..."
      - mvn clean package -DskipTests

      # Copy WAR as ROOT.war at top level
      - cp target/*.war ROOT.war

      # Optional: verify JSPs exist in WAR
      - echo "Listing JSP files in WAR for verification:"
      - unzip -l ROOT.war | grep ".jsp" || echo "No JSP files found in WAR"

      # Zip the WAR at top level
      - zip app.zip ROOT.war

artifacts:
  files:
    - app.zip
