version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing zip..."
      - yum install -y zip
  build:
    commands:
      - echo "Building WAR for Elastic Beanstalk..."
      - mvn clean package -DskipTests
      - zip app.zip target/ROOT.war
artifacts:
  files:
    - app.zip
